### ISSUE TITLE
crash when trying to carry backpack

### ISSUE THREAD

**Issue by dynamiteOpanty** [Sunconure11/WearableBackpacks#11]
game crashes after following step:
put backpack block
exit world then join again (backpack bugs after this)
try to carry (to break while sneak) backpack, then crash
crash log:
[crash-2023-10-29_17.03.49-client.txt](https://github.com/Sunconure11/WearableBackpacks/files/13197540/crash-2023-10-29_17.03.49-client.txt)

opening backpack also gives error:

**Comment by dynamiteOpanty** [comment]
(sent in the middle)

the error:

> [17:03:41] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@32f73705, suppressing error
> java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2371.get(int)" because the return value of "net.minecraft.class_2621.method_11282()" is null
> 	at net.minecraft.class_2621.method_5438(class_2621.java:100) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_1735.method_7677(class_1735.java:53) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_1703.method_7623(class_1703.java:173) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_1703.method_7596(class_1703.java:138) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_3222.method_14235(class_3222.java:409) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_3222.method_17355(class_3222.java:1048) ~[client-intermediary.jar:?]
> 	at dev.sapphic.wearablebackpacks.block.BackpackBlock.method_9534(BackpackBlock.java:158) ~[wearablebackpacks-4.0.0.jar:?]
> 	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:964) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_3225.method_14262(class_3225.java:338) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_3244.method_12046(class_3244.java:1145) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[client-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[client-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[client-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[client-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[client-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
> 	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by Sunconure11** [comment]
We are aware there is an issue with Sodium. However, while it is partially fixed, I do not want to send out an incomplete fix.

**Comment by dynamiteOpanty** [comment]
but this problem occur without sodium

**Comment by Sunconure11** [comment]
Odd.

**Comment by Sunconure11** [comment]
I've pushed out a new build. See if it works.

**Comment by dynamiteOpanty** [comment]
builded on the commit:
12a9c78bd208c6fefb9f37dec573f34cd32a7628

still same problem.
[latest.log](https://github.com/Sunconure11/WearableBackpacks/files/13575526/latest.log)

**Comment by Sunconure11** [comment]
New build has been pushed. See if this works.
