### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Mouy07** [Sunconure11/WearableBackpacks#7]
**Minecraft Version**
1.19.2

**Loader Version**
Fabric 0.14.22

**Details**
The game crashes while launching. Only Wearable Backpacks and Fabric API are installed.

**Crash Report**
[crash-2023-09-10_14.23.12-client.txt](https://github.com/Sunconure11/WearableBackpacks/files/12570032/crash-2023-09-10_14.23.12-client.txt)

**Comment by Sunconure11** [comment]
Download Cloth Config.
